2023-12-29-10-01-41-973131
Traceback of setup call:
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\spyder_kernels\console\__main__.py", line 24, in <module>
    start.main()
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\spyder_kernels\console\start.py", line 330, in main
    kernel.start()
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\IPython\core\interactiveshell.py", line 3009, in run_cell
    result = self._run_cell(
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\IPython\core\interactiveshell.py", line 3064, in _run_cell
    result = runner(coro)
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\IPython\core\interactiveshell.py", line 3269, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\IPython\core\interactiveshell.py", line 3448, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\pedro_8k2kvrz\AppData\Local\Temp\ipykernel_16944\4144374116.py", line 1, in <module>
    runfile('C:/Users/pedro_8k2kvrz/OneDrive - Universidade do Porto/Portatil_neuro/Documentos/Scripts_Spinnaker/Coincidence_detection.py', wdir='C:/Users/pedro_8k2kvrz/OneDrive - Universidade do Porto/Portatil_neuro/Documentos/Scripts_Spinnaker')
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 528, in runfile
    return _exec_file(
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 615, in _exec_file
    exec_code(file_code, filename, ns_globals, ns_locals,
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 473, in exec_code
    exec_fun(compile(ast_code, filename, 'exec'), ns_globals, ns_locals)
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
  File "c:\users\pedro_8k2kvrz\onedrive - universidade do porto\portatil_neuro\documentos\scripts_spinnaker\coincidence_detection.py", line 14, in <module>
    sim.setup(timestep=1.0)
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\spynnaker\pyNN\__init__.py", line 279, in setup
    __simulator = SpiNNaker(
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\spynnaker\pyNN\spinnaker.py", line 111, in __init__
    super().__init__(
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\spinn_front_end_common\interface\abstract_spinnaker_base.py", line 208, in __init__
    self._set_up_report_specifics()
  File "C:\Users\pedro_8k2kvrz\.conda\envs\env38\lib\site-packages\spinn_front_end_common\interface\config_handler.py", line 201, in _set_up_report_specifics
    traceback.print_stack(file=f)
